// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0j450SaBlgrJ85M4jBwuctLoV-6qHZuc',
    appId: '1:590135765567:web:1ab88e85290d82a4d1e68a',
    messagingSenderId: '590135765567',
    projectId: 'flutterauth-1231c',
    authDomain: 'flutterauth-1231c.firebaseapp.com',
    storageBucket: 'flutterauth-1231c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiejG4W9A5VNnAvodL5QMwoBklE-CsvLw',
    appId: '1:590135765567:android:f16e2f94e1ea0fb0d1e68a',
    messagingSenderId: '590135765567',
    projectId: 'flutterauth-1231c',
    storageBucket: 'flutterauth-1231c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN0tvDhk_QrJ46vxPKozgSp_PONiNJuJc',
    appId: '1:590135765567:ios:f9da1b6b0f3eee3fd1e68a',
    messagingSenderId: '590135765567',
    projectId: 'flutterauth-1231c',
    storageBucket: 'flutterauth-1231c.appspot.com',
    iosBundleId: 'com.example.flutterauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0tvDhk_QrJ46vxPKozgSp_PONiNJuJc',
    appId: '1:590135765567:ios:3c077c14e1eae971d1e68a',
    messagingSenderId: '590135765567',
    projectId: 'flutterauth-1231c',
    storageBucket: 'flutterauth-1231c.appspot.com',
    iosBundleId: 'com.example.flutterauth.RunnerTests',
  );
}
